### PR TITLE
Update MainProgram.py

### PR DESCRIPTION
**Pull request by Ali-Panagia**

### CODE REVIEW

**Comment by rolandlabana** [comment]
> _ No description provided. _

pls add a comment for this submission.

**Comment by Ali-Panagia** [comment]
Like a comment here or a different comment?

**Comment by rolandlabana** [comment]
> Like a comment here or a different comment?

Yes the comment might say something like "added my name to print in the file."

**Comment by Ali-Panagia** [comment]
Ok I get it now. Thank you for this information.

**Comment by rolandlabana** [comment]
> Ok I get it now. Thank you for this information.

ok, when you leave a good description I'll approve this

**Comment by Ali-Panagia** [comment]
Sorry. I've added my name to the main program.

**Pull request merged**
