### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Naggar0**

### CODE REVIEW

**Comment by rolandlabana** [comment]
Pls add a comment to this submission.

**Comment by Naggar0** [comment]
Is the comment going to be my name and date?

**Comment by rolandlabana** [comment]
no, I'm talking about the comment to list the purpose of your submission.
But the assignment (part of it) is to update the file with a comment - but
that's not what i'm referring to here.
I'm referring to the submission comment - like what are the changes you are
submitting - what is the new feature or bug you fixed?

**Comment by Naggar0** [comment]
Ok I’ll figure it out, thank you

**Pull request closed without merging**
