### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JudahJ**
Please add my name "Judah" to the read me file.

### CODE REVIEW

**Comment by JudahJ** [comment]
I watched a ted talk the other day. This Ted Talk was about the falsely conceived notion that something great comes from a single slice of genius. Linda Hill explained that significant innovation is born from many collective minds. To get this point across Linda used an experience she had from studying Pixar Animation. To make the movie Ratatouille, 250 people were involved in the story writing and animation. Every single person added a slice of their genius in order to make the movie whole. An example of this is one of the animators who decided to add an arched eyebrow in order to exhibit malicious intent. This subtle difference, though slightly, impacted the movie in a positive way. This is what Ms. Hill means by “You have to unleash the talents and you have to harness them into a work that is actually useful”. While I agree with Linda’s point, I also think that there are special cases. For example, Jeff Bezos started his company, Amazon, in a garage by himself, but to Linda’s argument, it is true that many more great ideas are done through the work of many.

**Review by rolandlabana — CHANGES_REQUESTED** [review]
Pls update with better comment on the submission. ie: not the whole paste of philosophy

**Comment by JudahJ** [comment]
Python is commonly used for developing websites and software, task automation, data analysis, and data visualization. Since it's relatively easy to learn, Python has been adopted by many non-programmers such as accountants and scientists, for a variety of everyday tasks, like organizing finances.

**Comment by rolandlabana** [comment]
Hi Judah, this comment is not the on you want either.
Pls add a comment more like this and understand why I've requested this.
"Add my name Judah to the ReadMe file"

**Comment by rolandlabana** [comment]
I'll close this request because i see you've submitted new ones.

**Pull request closed without merging**
